### ISSUE TITLE
Cannot read from database

### ISSUE THREAD

**Issue by marclllaks** [Brunya/zbase-board#2]
(print "The database: " (str @app-state))
The code seen on the top doesn't seem to work. Maybe I should read from the database with a cmc/read or cmc/from kind of thing? (Tested both of them, but it doesn't work).

**Comment by liszper** [comment]
The problem is from async. The database always initialize with a nil value first and only get the newest data later (0.3s) after the connection was established.

One thing was missing: cc/init needed a ":reagent? true" parameter to be compatible with Reagent and work in the UI

I added (str @app-state) into the UI then and it worked.

**Comment by liszper** [comment]
basically you wanted to see the the value too early, before the server provided it
